# Generated by Django 4.1.7 on 2023-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless_mail', '0020_mailaccount_is_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrule',
            name='scan_subfolders',
            field=models.BooleanField(default=False, verbose_name='scan subfolders'),
        ),
    ]
